name: Munual
on:
  workflow_dispatch: # 手動実行イベント
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: munual
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{inputs.greeting}}" # greetingのインプットを参照する
